namespace Anvil.Instructions;

public static class OperationCodeMapping
{
    private static readonly Dictionary<OperationCode, InstructionInfo> Mapping = new()
    {
        // Zero operand
        [OperationCode.NOP] = new(0, Array.Empty<int>()),
        [OperationCode.ACONST_NULL] = new(0, Array.Empty<int>()),
        [OperationCode.ICONST_M1] = new(0, Array.Empty<int>()),
        [OperationCode.ICONST_0] = new(0, Array.Empty<int>()),
        [OperationCode.ICONST_1] = new(0, Array.Empty<int>()),
        [OperationCode.ICONST_2] = new(0, Array.Empty<int>()),
        [OperationCode.ICONST_3] = new(0, Array.Empty<int>()),
        [OperationCode.ICONST_4] = new(0, Array.Empty<int>()),
        [OperationCode.ICONST_5] = new(0, Array.Empty<int>()),
        [OperationCode.LCONST_0] = new(0, Array.Empty<int>()),
        [OperationCode.LCONST_1] = new(0, Array.Empty<int>()),
        [OperationCode.FCONST_0] = new(0, Array.Empty<int>()),
        [OperationCode.FCONST_1] = new(0, Array.Empty<int>()),
        [OperationCode.FCONST_2] = new(0, Array.Empty<int>()),
        [OperationCode.DCONST_0] = new(0, Array.Empty<int>()),
        [OperationCode.DCONST_1] = new(0, Array.Empty<int>()),
        [OperationCode.IALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.LALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.FALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.DALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.AALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.BALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.CALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.SALOAD] = new(0, Array.Empty<int>()),
        [OperationCode.IASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.LASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.FASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.DASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.AASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.BASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.CASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.SASTORE] = new(0, Array.Empty<int>()),
        [OperationCode.POP] = new(0, Array.Empty<int>()),
        [OperationCode.POP2] = new(0, Array.Empty<int>()),
        [OperationCode.DUP] = new(0, Array.Empty<int>()),
        [OperationCode.DUP_X1] = new(0, Array.Empty<int>()),
        [OperationCode.DUP_X2] = new(0, Array.Empty<int>()),
        [OperationCode.DUP2] = new(0, Array.Empty<int>()),
        [OperationCode.DUP2_X1] = new(0, Array.Empty<int>()),
        [OperationCode.DUP2_X2] = new(0, Array.Empty<int>()),
        [OperationCode.SWAP] = new(0, Array.Empty<int>()),
        [OperationCode.IADD] = new(0, Array.Empty<int>()),
        [OperationCode.LADD] = new(0, Array.Empty<int>()),
        [OperationCode.FADD] = new(0, Array.Empty<int>()),
        [OperationCode.DADD] = new(0, Array.Empty<int>()),
        [OperationCode.ISUB] = new(0, Array.Empty<int>()),
        [OperationCode.LSUB] = new(0, Array.Empty<int>()),
        [OperationCode.FSUB] = new(0, Array.Empty<int>()),
        [OperationCode.DSUB] = new(0, Array.Empty<int>()),
        [OperationCode.IMUL] = new(0, Array.Empty<int>()),
        [OperationCode.LMUL] = new(0, Array.Empty<int>()),
        [OperationCode.FMUL] = new(0, Array.Empty<int>()),
        [OperationCode.DMUL] = new(0, Array.Empty<int>()),
        [OperationCode.IDIV] = new(0, Array.Empty<int>()),
        [OperationCode.LDIV] = new(0, Array.Empty<int>()),
        [OperationCode.FDIV] = new(0, Array.Empty<int>()),
        [OperationCode.DDIV] = new(0, Array.Empty<int>()),
        [OperationCode.IREM] = new(0, Array.Empty<int>()),
        [OperationCode.LREM] = new(0, Array.Empty<int>()),
        [OperationCode.FREM] = new(0, Array.Empty<int>()),
        [OperationCode.DREM] = new(0, Array.Empty<int>()),
        [OperationCode.INEG] = new(0, Array.Empty<int>()),
        [OperationCode.LNEG] = new(0, Array.Empty<int>()),
        [OperationCode.FNEG] = new(0, Array.Empty<int>()),
        [OperationCode.DNEG] = new(0, Array.Empty<int>()),
        [OperationCode.ISHL] = new(0, Array.Empty<int>()),
        [OperationCode.LSHL] = new(0, Array.Empty<int>()),
        [OperationCode.ISHR] = new(0, Array.Empty<int>()),
        [OperationCode.LSHR] = new(0, Array.Empty<int>()),
        [OperationCode.IUSHR] = new(0, Array.Empty<int>()),
        [OperationCode.LUSHR] = new(0, Array.Empty<int>()),
        [OperationCode.IAND] = new(0, Array.Empty<int>()),
        [OperationCode.LAND] = new(0, Array.Empty<int>()),
        [OperationCode.IOR] = new(0, Array.Empty<int>()),
        [OperationCode.LOR] = new(0, Array.Empty<int>()),
        [OperationCode.IXOR] = new(0, Array.Empty<int>()),
        [OperationCode.LXOR] = new(0, Array.Empty<int>()),
        [OperationCode.I2L] = new(0, Array.Empty<int>()),
        [OperationCode.I2F] = new(0, Array.Empty<int>()),
        [OperationCode.I2D] = new(0, Array.Empty<int>()),
        [OperationCode.L2I] = new(0, Array.Empty<int>()),
        [OperationCode.L2F] = new(0, Array.Empty<int>()),
        [OperationCode.L2D] = new(0, Array.Empty<int>()),
        [OperationCode.F2I] = new(0, Array.Empty<int>()),
        [OperationCode.F2L] = new(0, Array.Empty<int>()),
        [OperationCode.F2D] = new(0, Array.Empty<int>()),
        [OperationCode.D2I] = new(0, Array.Empty<int>()),
        [OperationCode.D2L] = new(0, Array.Empty<int>()),
        [OperationCode.D2F] = new(0, Array.Empty<int>()),
        [OperationCode.I2B] = new(0, Array.Empty<int>()),
        [OperationCode.I2C] = new(0, Array.Empty<int>()),
        [OperationCode.I2S] = new(0, Array.Empty<int>()),
        [OperationCode.LCMP] = new(0, Array.Empty<int>()),
        [OperationCode.FCMPL] = new(0, Array.Empty<int>()),
        [OperationCode.FCMPG] = new(0, Array.Empty<int>()),
        [OperationCode.DCMPL] = new(0, Array.Empty<int>()),
        [OperationCode.DCMPG] = new(0, Array.Empty<int>()),
        [OperationCode.ARRAYLENGTH] = new(0, Array.Empty<int>()),
        [OperationCode.ATHROW] = new(0, Array.Empty<int>()),
        [OperationCode.MONITORENTER] = new(0, Array.Empty<int>()),
        [OperationCode.MONITOREXIT] = new(0, Array.Empty<int>()),
        [OperationCode.IRETURN] = new(0, Array.Empty<int>()),
        [OperationCode.LRETURN] = new(0, Array.Empty<int>()),
        [OperationCode.FRETURN] = new(0, Array.Empty<int>()),
        [OperationCode.DRETURN] = new(0, Array.Empty<int>()),
        [OperationCode.ARETURN] = new(0, Array.Empty<int>()),
        [OperationCode.RETURN] = new(0, Array.Empty<int>()),

        // 单操作数
        [OperationCode.BIPUSH] = new(1, new[] { 1 }),
        [OperationCode.SIPUSH] = new(1, new[] { 2 }),
        [OperationCode.LDC] = new(1, new[] { 1 }),
        [OperationCode.LDC_W] = new(1, new[] { 2 }),
        [OperationCode.LDC2_W] = new(1, new[] { 2 }),
        [OperationCode.ILOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.LLOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.FLOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.DLOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.ALOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.ISTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.LSTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.FSTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.DSTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.ASTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.RET] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.IINC] = new(2, new[] { 1, 1 }, canBeWide: true),
        [OperationCode.NEWARRAY] = new(1, new[] { 1 }),
        [OperationCode.NEW] = new(1, new[] { 2 }),
        [OperationCode.ANEWARRAY] = new(1, new[] { 2 }),
        [OperationCode.CHECKCAST] = new(1, new[] { 2 }),
        [OperationCode.INSTANCEOF] = new(1, new[] { 2 }),
        [OperationCode.GETSTATIC] = new(1, new[] { 2 }),
        [OperationCode.PUTSTATIC] = new(1, new[] { 2 }),
        [OperationCode.GETFIELD] = new(1, new[] { 2 }),
        [OperationCode.PUTFIELD] = new(1, new[] { 2 }),
        [OperationCode.INVOKEVIRTUAL] = new(1, new[] { 2 }),
        [OperationCode.INVOKESPECIAL] = new(1, new[] { 2 }),
        [OperationCode.INVOKESTATIC] = new(1, new[] { 2 }),
        [OperationCode.INVOKEDYNAMIC] = new(2, new[] { 2, 2 }), // bootstrap + name/type
        [OperationCode.IFEQ] = new(1, new[] { 2 }),
        [OperationCode.IFNE] = new(1, new[] { 2 }),
        [OperationCode.IFLT] = new(1, new[] { 2 }),
        [OperationCode.IFGE] = new(1, new[] { 2 }),
        [OperationCode.IFGT] = new(1, new[] { 2 }),
        [OperationCode.IFLE] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPEQ] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPNE] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPLT] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPGE] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPGT] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPLE] = new(1, new[] { 2 }),
        [OperationCode.IF_ACMPEQ] = new(1, new[] { 2 }),
        [OperationCode.IF_ACMPNE] = new(1, new[] { 2 }),
        [OperationCode.IFNULL] = new(1, new[] { 2 }),
        [OperationCode.IFNONNULL] = new(1, new[] { 2 }),
        [OperationCode.GOTO] = new(1, new[] { 2 }),
        [OperationCode.JSR] = new(1, new[] { 2 }),
        [OperationCode.GOTO_W] = new(1, new[] { 4 }),
        [OperationCode.JSR_W] = new(1, new[] { 4 }),

        // Special multiple operands
        [OperationCode.INVOKEINTERFACE] = new(3, new[] { 2, 1, 1 }),
        [OperationCode.MULTIANEWARRAY] = new(2, new[] { 2, 1 }),
    };

    public class InstructionInfo
    {
        public int OperandCount { get; }
        public int[] OperandSizes { get; }
        public bool CanBeWide { get; }

        public InstructionInfo(int count, int[] sizes, bool canBeWide = false)
        {
            OperandCount = count;
            OperandSizes = sizes;
            CanBeWide = canBeWide;
        }
    }

    public static bool TryGetInfo(OperationCode op, out InstructionInfo? info)
        => Mapping.TryGetValue(op, out info);
}