namespace Anvil.Instructions;

public static class OperationCodeMapping
{
    // Cache the empty array to reduce allocations
    private static readonly int[] NoOperands = Array.Empty<int>();
    
    // Helper for cleaner initialization
    private static InstructionInfo ZeroOp() => new(0, NoOperands);

    private static readonly Dictionary<OperationCode, InstructionInfo> Mapping = new()
    {
        // Zero operand instructions
        [OperationCode.NOP] = ZeroOp(),
        [OperationCode.ACONST_NULL] = ZeroOp(),
        [OperationCode.ICONST_M1] = ZeroOp(),
        [OperationCode.ICONST_0] = ZeroOp(),
        [OperationCode.ICONST_1] = ZeroOp(),
        [OperationCode.ICONST_2] = ZeroOp(),
        [OperationCode.ICONST_3] = ZeroOp(),
        [OperationCode.ICONST_4] = ZeroOp(),
        [OperationCode.ICONST_5] = ZeroOp(),
        [OperationCode.LCONST_0] = ZeroOp(),
        [OperationCode.LCONST_1] = ZeroOp(),
        [OperationCode.FCONST_0] = ZeroOp(),
        [OperationCode.FCONST_1] = ZeroOp(),
        [OperationCode.FCONST_2] = ZeroOp(),
        [OperationCode.DCONST_0] = ZeroOp(),
        [OperationCode.DCONST_1] = ZeroOp(),
        [OperationCode.IALOAD] = ZeroOp(),
        [OperationCode.LALOAD] = ZeroOp(),
        [OperationCode.FALOAD] = ZeroOp(),
        [OperationCode.DALOAD] = ZeroOp(),
        [OperationCode.AALOAD] = ZeroOp(),
        [OperationCode.BALOAD] = ZeroOp(),
        [OperationCode.CALOAD] = ZeroOp(),
        [OperationCode.SALOAD] = ZeroOp(),
        [OperationCode.IASTORE] = ZeroOp(),
        [OperationCode.LASTORE] = ZeroOp(),
        [OperationCode.FASTORE] = ZeroOp(),
        [OperationCode.DASTORE] = ZeroOp(),
        [OperationCode.AASTORE] = ZeroOp(),
        [OperationCode.BASTORE] = ZeroOp(),
        [OperationCode.CASTORE] = ZeroOp(),
        [OperationCode.SASTORE] = ZeroOp(),
        [OperationCode.POP] = ZeroOp(),
        [OperationCode.POP2] = ZeroOp(),
        [OperationCode.DUP] = ZeroOp(),
        [OperationCode.DUP_X1] = ZeroOp(),
        [OperationCode.DUP_X2] = ZeroOp(),
        [OperationCode.DUP2] = ZeroOp(),
        [OperationCode.DUP2_X1] = ZeroOp(),
        [OperationCode.DUP2_X2] = ZeroOp(),
        [OperationCode.SWAP] = ZeroOp(),
        [OperationCode.IADD] = ZeroOp(),
        [OperationCode.LADD] = ZeroOp(),
        [OperationCode.FADD] = ZeroOp(),
        [OperationCode.DADD] = ZeroOp(),
        [OperationCode.ISUB] = ZeroOp(),
        [OperationCode.LSUB] = ZeroOp(),
        [OperationCode.FSUB] = ZeroOp(),
        [OperationCode.DSUB] = ZeroOp(),
        [OperationCode.IMUL] = ZeroOp(),
        [OperationCode.LMUL] = ZeroOp(),
        [OperationCode.FMUL] = ZeroOp(),
        [OperationCode.DMUL] = ZeroOp(),
        [OperationCode.IDIV] = ZeroOp(),
        [OperationCode.LDIV] = ZeroOp(),
        [OperationCode.FDIV] = ZeroOp(),
        [OperationCode.DDIV] = ZeroOp(),
        [OperationCode.IREM] = ZeroOp(),
        [OperationCode.LREM] = ZeroOp(),
        [OperationCode.FREM] = ZeroOp(),
        [OperationCode.DREM] = ZeroOp(),
        [OperationCode.INEG] = ZeroOp(),
        [OperationCode.LNEG] = ZeroOp(),
        [OperationCode.FNEG] = ZeroOp(),
        [OperationCode.DNEG] = ZeroOp(),
        [OperationCode.ISHL] = ZeroOp(),
        [OperationCode.LSHL] = ZeroOp(),
        [OperationCode.ISHR] = ZeroOp(),
        [OperationCode.LSHR] = ZeroOp(),
        [OperationCode.IUSHR] = ZeroOp(),
        [OperationCode.LUSHR] = ZeroOp(),
        [OperationCode.IAND] = ZeroOp(),
        [OperationCode.LAND] = ZeroOp(),
        [OperationCode.IOR] = ZeroOp(),
        [OperationCode.LOR] = ZeroOp(),
        [OperationCode.IXOR] = ZeroOp(),
        [OperationCode.LXOR] = ZeroOp(),
        [OperationCode.I2L] = ZeroOp(),
        [OperationCode.I2F] = ZeroOp(),
        [OperationCode.I2D] = ZeroOp(),
        [OperationCode.L2I] = ZeroOp(),
        [OperationCode.L2F] = ZeroOp(),
        [OperationCode.L2D] = ZeroOp(),
        [OperationCode.F2I] = ZeroOp(),
        [OperationCode.F2L] = ZeroOp(),
        [OperationCode.F2D] = ZeroOp(),
        [OperationCode.D2I] = ZeroOp(),
        [OperationCode.D2L] = ZeroOp(),
        [OperationCode.D2F] = ZeroOp(),
        [OperationCode.I2B] = ZeroOp(),
        [OperationCode.I2C] = ZeroOp(),
        [OperationCode.I2S] = ZeroOp(),
        [OperationCode.LCMP] = ZeroOp(),
        [OperationCode.FCMPL] = ZeroOp(),
        [OperationCode.FCMPG] = ZeroOp(),
        [OperationCode.DCMPL] = ZeroOp(),
        [OperationCode.DCMPG] = ZeroOp(),
        [OperationCode.ARRAYLENGTH] = ZeroOp(),
        [OperationCode.ATHROW] = ZeroOp(),
        [OperationCode.MONITORENTER] = ZeroOp(),
        [OperationCode.MONITOREXIT] = ZeroOp(),
        [OperationCode.IRETURN] = ZeroOp(),
        [OperationCode.LRETURN] = ZeroOp(),
        [OperationCode.FRETURN] = ZeroOp(),
        [OperationCode.DRETURN] = ZeroOp(),
        [OperationCode.ARETURN] = ZeroOp(),
        [OperationCode.RETURN] = ZeroOp(),

        // Single operand instructions
        [OperationCode.BIPUSH] = new(1, new[] { 1 }),
        [OperationCode.SIPUSH] = new(1, new[] { 2 }),
        [OperationCode.LDC] = new(1, new[] { 1 }),
        [OperationCode.LDC_W] = new(1, new[] { 2 }),
        [OperationCode.LDC2_W] = new(1, new[] { 2 }),
        [OperationCode.ILOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.LLOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.FLOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.DLOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.ALOAD] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.ISTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.LSTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.FSTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.DSTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.ASTORE] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.RET] = new(1, new[] { 1 }, canBeWide: true),
        [OperationCode.IINC] = new(2, new[] { 1, 1 }, canBeWide: true),
        [OperationCode.NEWARRAY] = new(1, new[] { 1 }),
        [OperationCode.NEW] = new(1, new[] { 2 }),
        [OperationCode.ANEWARRAY] = new(1, new[] { 2 }),
        [OperationCode.CHECKCAST] = new(1, new[] { 2 }),
        [OperationCode.INSTANCEOF] = new(1, new[] { 2 }),
        [OperationCode.GETSTATIC] = new(1, new[] { 2 }),
        [OperationCode.PUTSTATIC] = new(1, new[] { 2 }),
        [OperationCode.GETFIELD] = new(1, new[] { 2 }),
        [OperationCode.PUTFIELD] = new(1, new[] { 2 }),
        [OperationCode.INVOKEVIRTUAL] = new(1, new[] { 2 }),
        [OperationCode.INVOKESPECIAL] = new(1, new[] { 2 }),
        [OperationCode.INVOKESTATIC] = new(1, new[] { 2 }),
        [OperationCode.INVOKEDYNAMIC] = new(2, new[] { 2, 2 }), // bootstrap_method_attr_index + name_and_type_index
        [OperationCode.IFEQ] = new(1, new[] { 2 }),
        [OperationCode.IFNE] = new(1, new[] { 2 }),
        [OperationCode.IFLT] = new(1, new[] { 2 }),
        [OperationCode.IFGE] = new(1, new[] { 2 }),
        [OperationCode.IFGT] = new(1, new[] { 2 }),
        [OperationCode.IFLE] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPEQ] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPNE] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPLT] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPGE] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPGT] = new(1, new[] { 2 }),
        [OperationCode.IF_ICMPLE] = new(1, new[] { 2 }),
        [OperationCode.IF_ACMPEQ] = new(1, new[] { 2 }),
        [OperationCode.IF_ACMPNE] = new(1, new[] { 2 }),
        [OperationCode.IFNULL] = new(1, new[] { 2 }),
        [OperationCode.IFNONNULL] = new(1, new[] { 2 }),
        [OperationCode.GOTO] = new(1, new[] { 2 }),
        [OperationCode.JSR] = new(1, new[] { 2 }),
        [OperationCode.GOTO_W] = new(1, new[] { 4 }),
        [OperationCode.JSR_W] = new(1, new[] { 4 }),

        // Special multiple operands instructions
        [OperationCode.INVOKEINTERFACE] = new(3, new[] { 2, 1, 1 }),
        [OperationCode.MULTIANEWARRAY] = new(2, new[] { 2, 1 }),
    };

    public class InstructionInfo
    {
        public int OperandCount { get; }
        public int[] OperandSizes { get; }
        public bool CanBeWide { get; }

        public InstructionInfo(int count, int[] sizes, bool canBeWide = false)
        {
            OperandCount = count;
            OperandSizes = sizes;
            CanBeWide = canBeWide;
        }
    }

    public static bool TryGetInfo(OperationCode op, out InstructionInfo? info)
        => Mapping.TryGetValue(op, out info);
}
